name: "ðŸŒ€ â€¢ Build Fordy's YouTube Music+"

on:
  workflow_dispatch:
    inputs: 
      version:
        description: "Version (e.g. 1.0.0)"
        required: true
        type: string

      display_name:
        description: "App Name (Optional)"
        default: "YTMusic+ðŸ—¿"
        required: true
        type: string

      bundle_id:
        description: "BundleID (Optional)"
        default: "com.google.ios.youtubemusic"
        required: true
        type: string

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build YTMusicUltimate
    runs-on: macos-14
    permissions:
      contents: write

    steps:
      - name: Checkout Main
        uses: actions/checkout@v4
        with:
          path: main
          submodules: recursive

      - name: Hide sensitive inputs
        uses: levibostian/action-hide-sensitive-inputs@v1

      - name: Download and validate IPA
        run: |
          ASSET_URL=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/${{ github.repository }}/releases/tags/src" | jq -r '.assets[] | select(.name == "src.ipa") | .url')
          if [ -z "$ASSET_URL" ] || [ "$ASSET_URL" == "null" ]; then
            echo "::error:: src.ipa not found in release tagged 'src'."
            exit 1
          fi
          curl -L -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -H "Accept: application/octet-stream" "$ASSET_URL" -o ${{ github.workspace }}/src.ipa
          
          file_type=$(file --mime-type -b ${{ github.workspace }}/src.ipa)
          if [[ "$file_type" != "application/x-ios-app" && "$file_type" != "application/zip" ]]; then
            echo "::error::Validation failed: The file is not a valid IPA."
            exit 1
          fi

      - name: Download custom icon
        run: |
          icon_url="https://raw.githubusercontent.com/${{ github.repository }}/refs/heads/main/custom/icon.png"
          wget "$icon_url" --no-verbose -O ${{ github.workspace }}/icon.png

      - name: Install Dependencies
        run: brew install make ldid

      - name: Set PATH environment variable
        run: echo "$(brew --prefix make)/libexec/gnubin" >> $GITHUB_PATH

      - name: Cache Theos
        id: theos
        uses: actions/cache@v4.3.0
        env:
          cache-name: theos_cache_67db2ab
        with:
          path: theos/
          key: ${{ env.cache-name }}
          restore-keys: ${{ env.cache-name }}

      - name: Setup Theos
        if: steps.theos.outputs.cache-hit != 'true'
        uses: actions/checkout@v5
        with:
          repository: theos/theos
          ref: 67db2ab8d950910161730de77c322658ea3e6b44
          path: ${{ github.workspace }}/theos
          submodules: recursive

      - name: Download iOS SDK
        if: steps.theos.outputs.cache-hit != 'true'
        run: |
          git clone --quiet -n --depth=1 --filter=tree:0 https://github.com/theos/sdks/
          cd sdks
          git sparse-checkout set --no-cone iPhoneOS16.5.sdk
          git checkout
          mv *.sdk $THEOS/sdks
        env:
          THEOS: ${{ github.workspace }}/theos

      - name: Install Cyan and dependencies
        run: |
          pipx install --force https://github.com/asdfzxcvbn/pyzule-rw/archive/main.zip
          pipx inject cyan Pillow

      - name: Build Tweak for Sideloading
        id: build_package
        run: |
          cd ${{ github.workspace }}/main
          make clean package SIDELOADING=1
        env:
          THEOS: ${{ github.workspace }}/theos

      - name: Inject tweak into provided IPA
        run: |
          cd ${{ github.workspace }}/main/packages
          tweakName=$(ls *.deb)
          cd ${{ github.workspace }}/main
          cyan -i ${{ github.workspace }}/src.ipa -o ${{ github.workspace }}/FordyYTM_${{ inputs.version }}.ipa -k ${{ github.workspace }}/icon.png -uwef packages/$tweakName -n "${{ inputs.display_name }}" -b ${{ inputs.bundle_id }} 

      - name: Create Release
        uses: softprops/action-gh-release@v2.4.1
        with:
          name: YTMusic+ðŸ—¿ v${{ inputs.version }}
          tag_name: v${{ inputs.version }}
          files: ${{ github.workspace }}/FordyYTM_${{ inputs.version }}.ipa
          draft: true

      - name: Output Release URL
        run: |
          echo "::notice::Release available at: https://github.com/${{ github.repository }}/releases"
